# Generated by Django 4.1.3 on 2022-12-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numbers',
            field=models.IntegerField(db_index=True, default=0, verbose_name='number'),
        ),
    ]
