# Generated by Django 4.1.3 on 2022-12-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='numbers',
            field=models.IntegerField(db_index=True, default=0, null=True, verbose_name='number'),
        ),
    ]
